spring.application.name=api-gateway
server.port=8090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#  Gateway Routing Rules

# Zone Service Routing
spring.cloud.gateway.server.webflux.routes[0].id=zone-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ZONE-SERVICE

spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/zones/**, /api/v1/zones

# Sensor Service Routing
spring.cloud.gateway.server.webflux.routes[1].id=sensor-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://SENSOR-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/sensors/**, /api/sensors

# Automation Service Routing
spring.cloud.gateway.server.webflux.routes[2].id=automation-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://AUTOMATION-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/automation/**, /api/automation

# Crop Service Routing
spring.cloud.gateway.server.webflux.routes[3].id=crop-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://CROP-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/crops/**, /api/v1/crops

# --- Logging for Debugging ---
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.cloud.gateway=TRACE

# Custom security property
agms.jwt.secret=bcd5bcc8555ca7d9f7cf971aecd33dc631a3b61bef110dcc2ba3634d4aaaf93d

eureka.instance.prefer-ip-address=true